<?php

namespace CineProject\PublicBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
	public function findCategoryAndMovies($id)
	{
		return $this->createQueryBuilder('c')
			->addSelect('m')
			->leftJoin('c.movies','m')
			->where('c.id = :id')
			->setParameter('id',$id)
			->getQuery()
			->getSingleResult();
	}
}
