cine_project_public_actor:
    resource: "@CineProjectPublicBundle/Resources/config/routing/actor.yml"
    prefix:   /

cine_project_public_film:
    resource: "@CineProjectPublicBundle/Resources/config/routing/movie.yml"
    prefix:  /film

cine_project_public_category:
    resource: "@CineProjectPublicBundle/Resources/config/routing/category.yml"
    prefix:  /category

cine_project_public_homepage:
    path:     /
    defaults: { _controller: CineProjectPublicBundle:Default:index }

cine_project_admin:
    path:     /admin
    defaults: { _controller: CineProjectPublicBundle:Admin:index }

cine_project_test_translation:
    path:     /{_locale}/test-translation
    defaults: { _controller: CineProjectPublicBundle:Test:translation }