cine_project_public_actor:
    resource: "@CineProjectPublicBundle/Resources/config/routing/actor.yml"
    prefix:   /acteur

cine_project_public_film:
    resource: "@CineProjectPublicBundle/Resources/config/routing/movie.yml"
    prefix:  /film

cine_project_public_homepage:
    path:     /
    defaults: { _controller: CineProjectPublicBundle:Default:index }
