actor_index:
    path:     /acteurs
    defaults: { _controller: "CineProjectPublicBundle:Actor:index" }
    methods:  GET

actor_show:
    path:     acteur/{slug}
    defaults: { _controller: "CineProjectPublicBundle:Actor:show" }
    methods:  GET

actor_new:
    path:     /ajouter-acteur
    defaults: { _controller: "CineProjectPublicBundle:Actor:new" }
    methods:  [GET, POST]

actor_edit:
    path:     /modifier-acteur/{slug}
    defaults: { _controller: "CineProjectPublicBundle:Actor:edit" }
    methods:  [GET, POST]

actor_delete:
    path:     /supprimer-acteur/{id}
    defaults: { _controller: "CineProjectPublicBundle:Actor:delete" }
    methods:  DELETE
