movie_index:
    path:     /
    defaults: { _controller: "CineProjectPublicBundle:Movie:index" }
    methods:  GET

movie_show:
    path:     /{id}/show
    defaults: { _controller: "CineProjectPublicBundle:Movie:show" }
    methods:  GET

movie_new:
    path:     /new
    defaults: { _controller: "CineProjectPublicBundle:Movie:new" }
    methods:  [GET, POST]

actor_edit:
    path:     /{id}/edit
    defaults: { _controller: "CineProjectPublicBundle:Actor:edit" }
    methods:  [GET, POST]

actor_delete:
    path:     /{id}/delete
    defaults: { _controller: "CineProjectPublicBundle:Actor:delete" }
    methods:  DELETE
